# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-  
    - name: Set up Python 3.7.6
      uses: actions/setup-python@v2
      with:
        python-version: "3.7.6"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m venv env
        source env/bin/activate
        pip3 install --upgrade pip
        pip3 install pytest
        if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
    - name: Set root directory
      run: |
        export PYTHONPATH=src
    - name: Test with pytest
      run: |
        pytest --record_path .
